name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: Program
        use-dependencies: true
        no-console: true

    - uses: actions/upload-artifact@v2
      with:
        name: grunwaldcalc
        path: ./dist/windows
